import type { NextPage } from "next";
import Head from "next/head";
import { useAuth } from "@clerk/nextjs";
import { useUser } from "../hooks";
import { NavigationLayout } from "../layouts";
import { ChatBox } from "../features";

import { GetChatRooms } from "../features/chat/get.chat.rooms";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const { isSignedIn } = useAuth();
  const user = useUser();
  // const { data: userData } = trpc.user.getUser.useQuery();

  // if (user && !userData) {
  //   const { mutate } = trpc.user.createUser.useMutation();
  //   mutate();
  // }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen flex-col items-center">
        <NavigationLayout />
        <ChatBox>{/* <GetChatRooms /> */}</ChatBox>
      </main>
    </>
  );
};

export default Home;
